---
name: SBFspot
version: 0.0.3
slug: sbfspot
description: SBFspot Add-On
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
url: https://github.com/bushvin/hassio-addons/tree/main/sbfspot
init: false
host_network: true
host_dbus: true
map:
  - share: rw
options:
  sbfspot_interval: 300
  connection_type: bluetooth
  inverter_bluetooth_address: "00:00:00:00:00:00"
  inverter_bluetooth_retries: 10
  inverter_password: "0000"
  inverter_ip_address: "0.0.0.0"
  local_bluetooth_address: "00:00:00:00:00:00"
  multi_inverter_support: false
  plantname: MyPlant
  inverter_latitude: 50.80
  inverter_longitude: 4.33
  inverter_cmsv: true
  datetime_format: "%d/%m/%Y %H:%M:%S"
  date_format: "%d/%m/%Y"
  time_format: "%H:%M:%S"
  field_delimiter: ","
  synctime: weekly
  synctime_low: 60
  synctime_high: 3600
  sunRSOffset: 900
  locale: en-US
  timezone: "Europe/Brussels"
  mqtt_export: true
  mqtt_publisher: /usr/bin/mosquitto_pub
  mqtt_hostname: test.mosquitto.org
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic: "sbfspot_{serial}"
  mqtt_format: json
  mqtt_arguments: []
  mqtt_data:
  - Timestamp
  - SunRise
  - SunSet
  - InvSerial
  - InvName
  - InvTime
  - InvStatus
  - InvTemperature
  - InvGridRelay
  - EToday
  - ETotal
  - PACTot
  - UDC
  - IDC
  - PDC
schema:
  sbfspot_interval: int
  connection_type: list(bluetooth|speedwire)
  inverter_bluetooth_address: str
  inverter_bluetooth_retries: int(1,15)
  inverter_password: password
  inverter_ip_address: str
  local_bluetooth_address: str
  multi_inverter_support: bool
  plantname: str
  inverter_latitude: float
  inverter_longitude: float
  inverter_cmsv: bool
  datetime_format: str
  date_format: str
  time_format: str
  field_delimiter: list(,|.)
  synctime: list(disabled|daily|weekly|monthly)
  synctime_low: int(1,120)
  synctime_high: int(1200,3600)
  sunRSOffset: int(0,3600)
  locale: str
  timezone: str
  mqtt_export: bool
  mqtt_publisher: str
  mqtt_hostname: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  mqtt_topic: str
  mqtt_format: list(json|text|xml)
  mqtt_arguments:
  - str?
  mqtt_data:
  - str

