---
name: SBFspot
version: 2025.2.0
slug: sbfspot
description: >-
  Get your inverter's data as a device and entities in Home Assistant using MQTT
stage: stable
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
url: https://github.com/bushvin/hassio-addons/tree/main/sbfspot
init: false
host_network: true
host_dbus: true
services:
  - mqtt:need
map:
  - share:rw
options:
  connection_type: bluetooth
  inverter_address: "00:00:00:00:00:00"
  inverter_password: "0000"
  local_address: "00:00:00:00:00:00"
  plant_name: "MyPlant"
  plant_latitude: 50.80
  plant_longitude: 4.33
  plant_timezone: "Europe/Brussels"
  mqtt_hostname: test.mosquitto.org
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  update_interval: 5
  sensor_action: run
  log_level: info

schema:
  connection_type: list(bluetooth|speedwire)
  inverter_address: str
  inverter_password: str
  local_address: str?
  plant_name: str
  plant_latitude: float
  plant_longitude: float
  plant_timezone: str
  mqtt_hostname: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  update_interval: list(1|5|10|15|30|60)?
  sensor_action: list(run|delete)?
  log_level: list(all|trace|debug|info|notice|warning|error|fatal|off)

