---
name: Restic Backups
version: 0.0.2
slug: restic
description: Simple backups using restic
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/bushvin/hassio-addons
map:
  - addons:ro
  - backup:ro
  - config:ro
  - media:ro
  - share:rw
  - ssl:ro
privileged:
  - DAC_READ_SEARCH
tmpfs: true
panel_icon: mdi:backup-restore
panel_title: Restic Backups
panel_admin: true

