---
name: Restic Backups
version: 0.0.9
slug: restic
description: Simple backups using restic
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/bushvin/hassio-addons
map:
  - addons:ro
  - backup:ro
  - config:ro
  - media:ro
  - share:rw
  - ssl:ro
privileged:
  - DAC_READ_SEARCH
tmpfs: true
panel_icon: mdi:backup-restore
panel_title: Restic Backups
panel_admin: true
options:
  restic_repository: /share/restic
  restic_password: ''
  restic_hostname: hassio
  restic_envvar: {}
  addons:
    enable_backup: false
    tags:
      - addons
    exclude: []
    enable_forget: true
    keep_daily: 24
    keep_weekly: 5
    keep_monthly: 12
    keep_yearly: 100
schema:
  restic_repository: str
  restic_password: password
  restic_hostname: str
  addons:
    enable_backup: bool
    tags:
      - str
    exclude:
      - str
    enable_forget: bool
    keep_daily: "int(0,31)"
    keep_weekly: "int(0,52)"
    keep_monthly: "int(0,12)"
    keep_yearly: "int(0,200)"

